### ISSUE TITLE
Alert deprecated: Toploop.directive_table [OCaml version 4.13.0~beta1]

### ISSUE THREAD

**Issue by Fourchaux** [dbuenzli/omod#13]
With :  
       
$ ocaml
                  OCaml version 4.13.0~beta1

#use "omod.top" ;;
-- : unit = ()
Omod v0.0.2 loaded. Type Omod.help () for more info.
-- : unit = ()
File "/home/bobo/.opam/4.13/lib/ocaml/omod.top", line 16, characters 28-51:
16 |      let is_utop = Hashtbl.mem Toploop.directive_table "utop_help" in
                                                                                     
**Alert** deprecated: Toploop.directive_table

**Comment by dbuenzli** [comment]
Thanks for the report. Any idea if there's a replacement ? What it is ? and if we can make it work pre 4.13 ?

**Comment by Fourchaux** [comment]
Sorry, I forgot the main info: the program seems OK .  

Omod.load "Foo" is working...

**Comment by dbuenzli** [comment]
Yeah sure it just looks like the [hack](https://github.com/dbuenzli/omod/blob/56663bdbd33590a68d9046928d2040dbf889120d/src/omod.top#L16) I use to detect utop is affected.

**Comment by Fourchaux** [comment]
Comment from OCaml trunk:
https://github.com/ocaml/ocaml/blob/trunk/toplevel/topcommon.mli#L150

**Comment by dbuenzli** [comment]
Mmmh that comment doesn't realize replacing a hashtable by a function does not offer the same functionality.

I don't see how we can really go about that further on. Except to split the init sequence in different files `omod.top` for `ocaml` and `omod.utop` for `utop`. 

A bit annoying.

**Comment by dbuenzli** [comment]
It's less reliable but maybe we could simply check `Sys.executable_name`.

**Comment by dbuenzli** [comment]
As side effect of moving the init sequences to the `omod` library, see #7, the warning now only happens at compilation time. 

Not a long term solution but at least we don't get this horrible shouting when we load `omod` – bonus point the package will fail compiling when the deprecated feature is removed. For now I prefer to [do this](https://github.com/dbuenzli/omod/blob/4f7ac08dccaa5fd1c9b2731fa199230e7121c471/src/omod_top.ml#L9) to detect utop rather than fiddling with `Sys.executable_name`. 

```ocaml 
> ocaml
        OCaml version 4.13.0

Down v0.0.4 loaded. Type Down.help () for more info.
Omod v0.0.2-19-g4f7ac08 loaded. Type Omod.help () for more info.
# 
```
