### ISSUE TITLE
 Unknown module name 'Toploop' in package 'ocaml'

### ISSUE THREAD

**Issue by samoht** [dbuenzli/omod#2]
Is that expected?

```
# #use "omod.top";;
- : unit = ()
Omod v0.0.1 loaded. Type Omod.help () for more info.
- : unit = ()
omod: [INDEXING] In progress...
[ERROR] Unknown module name 'Toploop' in package 'ocaml'.
```

Also I am not sure it is related, but I got:

```
# Omod.load "Ipaddr";;
[ERROR] Dependency 0fba23558da789bd0ef7ad786bdc90e6 Array cannot be resolved

- : bool = false
```

**Comment by dbuenzli** [comment]
Are you using a system switch ? https://github.com/dbuenzli/omod/issues/1

**Comment by samoht** [comment]
I thought not, but actually yes. Sorry for the noise ...

**Comment by dbuenzli** [comment]
No problem. And before you run into them (the modules `omod check -f | grep Native` can't be loaded because `nocrypto.mli` uses the packed `Native` module in its interface without declaring it. This is [fixed](https://github.com/mirleft/ocaml-nocrypto/blob/master/src/nocrypto.mli#L393-L394) (commented out) in `master` but not released. As you'll see it propagates a bit in the mirage libs though.

**Comment by dbuenzli** [comment]
Just in case this is now fixed in master, I'll wait a few days before making a release though.
