### ISSUE TITLE
Don't fail if Omod is loaded via ocamlfind

### ISSUE THREAD

**Issue by cfcs** [dbuenzli/omod#7]
First encountered here: https://github.com/dbuenzli/down/issues/19#issuecomment-516202068

```shell
~ export OCAMLRUNPARAM='b'
~ ocaml
        OCaml version 4.07.1

Findlib has been successfully loaded. Additional directives:
  #require "package";;      to load a package
  #list;;                   to list the available packages
  #camlp4o;;                to load camlp4 (standard syntax)
  #camlp4r;;                to load camlp4 (revised syntax)
  #predicates "p,q,...";;   to set these predicates
  Topfind.reset();;         to force that packages will be reloaded
  #thread;;                 to enable threads

Down v0.0.1 loaded. Type Down.help () for more info.
# #require "omod";;
/home/user/.opam/4.07.1/lib/omod: added to search path
/home/user/.opam/4.07.1/lib/omod/omod.cma: loaded
# Omod.load "unix";;
[INC] /home/user/.opam/4.07.1/lib/ocaml
[ERROR] include /home/user/.opam/4.07.1/lib/ocaml:
Unknown exception:
Invalid_argument
Raised at file "stdlib.ml", line 34, characters 25-45
Called from file "src/omod.ml", line 234, characters 14-25

- : bool = false
#
```

It's pretty likely that something in my environment is slightly broken; I had a lot of problems with `opam` when the folder containing a pinned project was removed, I'm not sure if what I'm seeing here is related.

I'm happy to provide more details or try out steps to debug as required. ping @dbuenzli

**Comment by cfcs** [comment]
Version info:
```shell
~ opam info omod down | egrep '(version|check)'
<><> down: information on all versions ><><><><><><><><><><><><><><><><><><><><>
all-installed-versions ~dev [4.07.1+afl]  0.0.1 [4.07.1]
all-versions           0.0.1
version       0.0.1
url.checksum: "md5=d224bb0d60da70fecd2fc5895bba9745"
<><> omod: information on all versions ><><><><><><><><><><><><><><><><><><><><>
all-installed-versions 0.0.2 [4.07.1 4.07.1+afl]
all-versions           0.0.1  0.0.2
version       0.0.2
url.checksum: "md5=98cb7bc813e9325237929d047cd8408b"
```

**Comment by dbuenzli** [comment]
Ah ok. I think I know what is happening. Don't `#require` this uses `ocamlfind` (which is somehow what you would like not to use :-).  You should invoke: 

```
#use "omod.top" (* or "omod.nattop" in ocamlnat *)
```

Basically since you `#require` the phrases in `omod.top` don't get executed which means that [the bit](https://github.com/dbuenzli/omod/blob/master/src/omod.top#L9) that sets the `Topdirs` API according to byte/native (a circumvolution needed because of point 4 here https://github.com/ocaml/ocaml/issues/7589) doesn't get executed and you get the default, failing API [here](https://github.com/dbuenzli/omod/blob/360253b1eada027282d1bba7cd61ea9ccae06fb8/src/omod.ml#L188-L194) (and for some reason the clear invalid arg error message is not printed).

That being said it may be possible to shift a bit things around so that this doesn't happen and that `omod` can be loaded by ocamlfind. For example `Down` does the toploop API [setup dance](https://github.com/dbuenzli/down/blob/04b55d7ece3f8a6f9e9099308f7f73abced02e21/src/down_top.ml) in the libraries rather than in the `.top` files which are kept to the [essential](https://github.com/dbuenzli/down/blob/master/src/down.top) to load the library.

**Comment by dbuenzli** [comment]
(and thanks for the details)

**Comment by cfcs** [comment]
Ah, thanks! I had the topfind loading directive in my `~/.ocamlinit` and didn't stop to think that it could be an issue. Now I've removed that, and `Omod.load` works :-)

**Comment by dbuenzli** [comment]
You can still have `topfind`. You should only not load `Omod` via `topfind` (i.e. via `#require` which is provided by `topfind`).

**Comment by dbuenzli** [comment]
In 1a73e7d311b879 and abb8bc31af10328 the init sequences where respectively moved to `omod.cma` and `omod_nattop.cmxs` mirroring what is done  by `down`. 

I still wouldn't recommend using both `omod` and `ocamlfind`, but you can now load `omod` via `ocamlfind`.
